apiVersion: v1
kind: Service
metadata:
  name: clb-direct-pod
  annotations:
    service.cloud.tencent.com/direct-access: "true"  # 启用直连 Pod 模式
spec:
  selector:
    app: real-ip-app  # 需匹配 Deployment 的标签
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer