controller:
  ingressClass: new-test # 新 IngressClass 名称，避免与现有 TKE 组件冲突
  ingressClassResource:
    name: new-test
    enabled: true
    controllerValue: k8s.io/new-test
  scope:
    enabled: true
    namespace: "ingress-nginx" # Nginx Controller监听处理指定命名空间下的Ingress资源 (可选)